version: '3'
services:
  db:
    image: mysql:5.7
    container_name: e2clothes_db
    ports:
      - "3307:3306"
    environment:
      # please remove this if in production and read the mysql docker doc
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    volumes:
      - ./tem/db:/var/lib/mysql
    networks:
      app_net:
        ipv4_address: 172.16.238.5

  rails_api:
    build: ./e2clothesBackend
    container_name: e2clothes_rails_api
    command: rails s --binding=0.0.0.0
    volumes:
      - "./e2clothesBackend:/app/api"
    ports:
      - "3000:3000"
    depends_on:
      - db
    links:
      - db
    environment:
      DB_HOST: db
    networks:
      app_net:
        ipv4_address: 172.16.238.2

  web:
    build: ./web
    container_name: e2clothes_frontend
    command: yarn start
    volumes:
      - './web:/app/web'
    ports:
      - "5000:5000"
    depends_on:
      - db
    networks:
      app_net:
        ipv4_address: 172.16.238.4

  graphql:
    build: ./graphql
    container_name: e2clothes_graphql
    command: npm run start
    volumes:
      - './graphql:/app/graphql'
    ports:
      - "4000:4000"
    environment:
      RAILS_URL: http://172.16.238.2:3000
    networks:
      app_net:
        ipv4_address: 172.16.238.3

networks:
  app_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.16.238.0/24
          gateway: 172.16.238.1
      
      
